name: ndef
description: A Dart library to decode & encode NDEF records, supporting multiple types.
version: 0.3.0
homepage: https://github.com/nfcim/ndef

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
