name: Test

on:
    push:
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, 'ci skip')"

        steps:
        - uses: actions/checkout@v2
        - uses: subosito/flutter-action@v1
          with:
            channel: 'stable'
        - run: flutter pub get
        - run: flutter test
        - name: Run example code
          run: |
            cd example
            dart pub get
            dart run lib/main.dart
